trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Terraform_plan
  jobs:
    - job: Plan
      continueOnError: false
      steps:
        # Paso 1: Instalar Terraform
        - task: TerraformInstaller@0
          inputs:
            terraformVersion: '1.5.7'  # Usa una versión específica
          displayName: 'Install Terraform'

        # Paso 2: Mostrar versión (opcional para verificación)
        - script: terraform --version
          displayName: 'Check Terraform version'

        # Paso 3: Terraform init
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
            backendServiceArm: 'Azure for Students(bfc3d097-7e73-40b8-aa34-e70b307c0867)'
            backendAzureRmResourceGroupName: 'VM'
            backendAzureRmStorageAccountName: 'vmrecursos'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'pipelines.tfstate'
          displayName: 'Terraform init'

        # Resto de tus pasos...
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
            environmentServiceNameAzureRM: 'Azure for Students(bfc3d097-7e73-40b8-aa34-e70b307c0867)'
          displayName: 'Terraform Plan'
      
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(System.DefaultWorkingDirectory)/terraform/plan.out'
            artifact: 'Plan'
            publishLocation: 'pipeline'
          displayName: 'Publish Plan Artifact'