trigger: none

variables:
  - group: variable-group-taller

steps:
- task: AzureCLI@2
  displayName: 'Eliminar grupo de recursos'
  inputs:
    azureSubscription: $(AZURE_ACCOUNT)
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group delete --name my-first-terraform-RG --yes --no-wait
      echo "Grupo de recursos eliminado o en proceso de eliminación"
