- name: Instalar dependencias para cryptography
  apt:
    name:
      - build-essential
      - libssl-dev
      - libffi-dev
      - python3-dev
      - cargo
    state: present
    update_cache: yes

- name: Instalar pip3
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Actualizar pip a la última versión
  command: python3 -m pip install --upgrade pip