- name: Clonar el repositorio
  git:
    repo: "https://github.com/Salazq/microservice-app-example.git"
    dest: /home/azureuser/tu-repo
    version: master

- name: Instalar docker-compose
  pip:
    name: docker-compose
    state: present

- name: Ejecutar docker-compose
  command: docker-compose -f Docker-compose.yml up -d
  args:
    chdir: /home/azureuser/tu-repo